title: "sean"
author: Sean Henderson
email: mail@sean.sh
description: > # this means to ignore newlines until outdented
  Sean's weblog: rants, musings, software speak, how-to's, developer-ese,
  and more.

disqus:
  shortname: sean-sh

permalink: /log/:title/
paginate: 5

# whitelist node_modules
exclude: []

# make npm packagaes available
sass:
  load_paths:
    - _sass
    - node_modules/materialize-css/sass

# social links
twitter_username: seanmh78
github_username:  sh78
linkedin_username: seanmhenderson
facebook_username: seanmhenderson
youtube_username: SeanHenderson7

rss: rss

# Mastodon instances
# mastodon:
# - username: sh78
#   instance: mastodon.technology
# - username: jekyll2
#   instance: example.com


# General options
show_excerpts: true # set to true to show excerpts on the blog page
truncate_excerpts: true # set to true to show excerpts on the blog page
post_columns: true # set to false to use a simple one column layout
post_cards: true
post_images: false
blog_posts_title: false # set to true to show the title on the blog page

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md
#   - blog.md

# Build settings
theme: minimaterialize

plugins:
 - jekyll-feed
 - jekyll-seo-tag
