title: Minimaterialize
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# whitelist node_modules
exclude: []

# make npm packagaes available
sass:
  load_paths:
    - _sass
    - node_modules/materialize-css/sass

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


# General options
show_excerpts: true # set to true to show excerpts on the homepage
truncate_excerpts: true # set to true to show excerpts on the homepage
post_columns: true # set to false to use a simple one column layout
post_cards: true
post_images: false
home_posts_title: false # set to true to show the title on the home page

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minimaterialize

plugins:
 - jekyll-feed
 - jekyll-seo-tag
